import { access, mkdir, readFile, writeFile } from 'node:fs/promises'
import { categories } from '../src/categories/registry'
import type { CategoryId, Product } from '../src/categories/types'

type NewProduct = Omit<Product, 'price' | 'stockQuantity'> & {
  priceKurus: number
  stockQuantity: number
}

const categoryIds: CategoryId[] = ['lighting', 'organizers', 'stationery', 'accessories']
const sqlString = (value: string) => `'${value.replaceAll("'", "''")}'`

async function main() {
  const rows: NewProduct[] = []
  for (const categoryId of categoryIds) {
    const existing = categories.find((category) => category.id === categoryId)?.products ?? []
    const added = JSON.parse(await readFile(new URL(`../data/seed/${categoryId}.json`, import.meta.url), 'utf8')) as NewProduct[]
    if (existing.length !== 3 || added.length !== 7) throw new Error(`${categoryId}: 3 mevcut ve 7 yeni ürün gerekli`)
    rows.push(...existing.map((product) => ({ ...product, priceKurus: Math.round(product.price * 100), stockQuantity: 20 })), ...added)
  }
  if (new Set(rows.map((row) => row.id)).size !== 40) throw new Error('Ürün kimlikleri benzersiz olmalı')
  for (const row of rows) {
    if (!categoryIds.includes(row.categoryId) || !row.id.startsWith(`${row.categoryId}-`)) throw new Error(`Geçersiz kategori/kimlik: ${row.id}`)
    if (!Number.isInteger(row.priceKurus) || row.priceKurus <= 0) throw new Error(`Geçersiz fiyat: ${row.id}`)
    if (!Number.isInteger(row.stockQuantity) || row.stockQuantity < 0) throw new Error(`Geçersiz stok: ${row.id}`)
    if (!row.image.startsWith(`/images/${row.categoryId}/`) || !row.gallery.every((path) => path.startsWith(`/images/${row.categoryId}/`))) throw new Error(`Geçersiz görsel yolu: ${row.id}`)
    for (const imagePath of new Set([row.image, ...row.gallery])) {
      await access(new URL(`../public${imagePath}`, import.meta.url))
    }
  }

  const values = rows.map((row, index) => {
    const fields = [row.id, row.categoryId, row.name, row.shortDescription, row.description, row.image, row.color, row.material, row.dimensions, row.detail]
    const gallery = `array[${row.gallery.map(sqlString).join(', ')}]::text[]`
    const badge = row.badge ? sqlString(row.badge) : 'null'
    return `  (${fields.slice(0, 5).map(sqlString).join(', ')}, ${row.priceKurus}, ${sqlString(row.image)}, ${gallery}, ${fields.slice(6).map(sqlString).join(', ')}, ${badge}, ${row.stockQuantity}, 'published', ${index})`
  })
  const sql = `-- Generated by npm run seed:build. Demo products, not real inventory.\n-- Existing rows are preserved so a later seed run cannot overwrite admin edits.\ninsert into public.products (id, category_id, name, short_description, description, price_kurus, image_url, gallery, color, material, dimensions, detail, badge, stock_quantity, status, sort_order)\nvalues\n${values.join(',\n')}\non conflict (id) do nothing;\n`
  await mkdir(new URL('../supabase/', import.meta.url), { recursive: true })
  await writeFile(new URL('../supabase/seed.sql', import.meta.url), sql)
  console.log(`supabase/seed.sql: ${rows.length} ürün`)
}

await main()
